{% set version = "1.3.0" %}

package:
  name: python-lsp-ruff
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/python-lsp-ruff/python-lsp-ruff-{{ version }}.tar.gz
  sha256: 7b9a9a19fee6a21e3442026cc579c8f654ceb9f58f63fb5a49f1c351f9576687

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - python-lsp-server
    - ruff >=0.0.260

test:
  source_files:
    - tests
  imports:
    - pylsp_ruff
  commands:
    - pip check
    - pytest -vv --cov=pylsp_ruff --cov-branch --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=86
  requires:
    - pip
    - pytest-cov

about:
  home: https://pypi.org/project/python-lsp-ruff
  summary: Ruff linting plugin for pylsp
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/python-lsp/python-lsp-ruff

extra:
  recipe-maintainers:
    - bollwyvl
    - jhossbach
